In [1]:
import pandas as pd
import seaborn as sns # For plotting
import matplotlib.pyplot as plt # For showing plots

In [13]:
df = pd.read_csv('INE_entire_database.csv', sep=",")
df.head(50)

,NutsID,DICOFRE,region_name,year,edu_none,edu_basic,edu_secondary,edu_superior,labour_family,labour_holder,...,olive_area,vineyards_area,other_permanent_crop_area,fresh_fruit_holdings,citrus_holdings,fruit_holdings,nuts_holdings,olive_holdings,vineyard_holdings,other_permanent_crop_holdings
0,111160101,160101,Aboim das ChoÃ§as,2019,15,61,11,7,34,15,...,0,12,0,0,1,0,1,0,32,0
1,111160101,160101,Aboim das ChoÃ§as,2009,30,57,4,4,50,24,...,0,9,0,0,0,0,0,0,29,0
2,111160101,160101,Aboim das ChoÃ§as,1999,49,73,7,6,62,26,...,0,14,0,0,0,0,0,0,40,0
3,111160101,160101,Aboim das ChoÃ§as,1989,167,97,4,0,163,70,...,0,28,0,0,0,0,0,1,84,0
4,111160102,160102,AguiÃ£,2019,24,68,5,2,70,38,...,1,15,0,0,0,0,0,2,39,0
5,111160102,160102,AguiÃ£,2009,23,82,8,4,66,38,...,0,17,0,0,0,0,2,0,42,0
6,111160102,160102,AguiÃ£,1999,71,99,2,2,78,37,...,0,20,0,0,0,0,0,0,54,0
7,111160102,160102,AguiÃ£,1989,94,220,2,0,178,66,...,1,14,0,1,2,0,0,6,79,0
8,111160104,160104,Ãzere,2019,3,48,12,5,18,11,...,0,7,0,2,2,0,3,4,18,0
9,111160104,160104,Ãzere,2009,28,42,2,6,29,17,...,0,5,0,0,1,0,0,1,25,0
10,111160104,160104,Ãzere,1999,46,56,0,2,55,24,...,0,8,0,4,2,0,0,2,30,0
11,111160104,160104,Ãzere,1989,76,60,4,1,89,33,...,0,12,0,3,0,0,1,1,39,0
12,111160105,160105,Cabana Maior,2019,24,34,5,0,25,15,...,0,2,0,0,0,0,0,0,12,0
13,111160105,160105,Cabana Maior,2009,42,22,1,0,33,19,...,0,1,0,0,0,0,0,0,23,0
14,111160105,160105,Cabana Maior,1999,80,77,2,0,98,53,...,0,6,0,1,1,0,0,0,52,0
15,111160105,160105,Cabana Maior,1989,212,75,7,1,187,89,...,1,5,0,0,1,0,0,5,79,0
16,111160106,160106,Cabreiro,2019,66,107,23,8,114,71,...,0,3,0,0,4,0,2,4,34,0
17,111160106,160106,Cabreiro,2009,152,104,8,4,177,90,...,0,7,0,0,0,0,0,3,101,0
18,111160106,160106,Cabreiro,1999,209,108,1,1,234,113,...,0,17,0,0,0,0,0,0,115,0
19,111160106,160106,Cabreiro,1989,402,290,1,0,423,174,...,0,22,0,0,0,0,0,3,183,0
20,111160108,160108,Cendufe,2019,5,35,6,4,30,17,...,0,9,0,0,0,0,6,0,21,0
21,111160108,160108,Cendufe,2009,32,61,14,3,69,32,...,0,11,0,0,3,0,1,4,40,0
22,111160108,160108,Cendufe,1999,83,90,9,7,75,38,...,0,17,0,0,0,0,0,3,56,0
23,111160108,160108,Cendufe,1989,117,150,13,1,165,65,...,2,19,0,2,1,0,1,44,80,4
24,111160109,160109,Couto,2019,13,70,17,4,26,13,...,0,7,0,3,1,0,4,5,21,0
25,111160109,160109,Couto,2009,24,45,4,1,38,19,...,0,3,0,1,0,0,1,0,25,0
26,111160109,160109,Couto,1999,80,93,7,2,70,35,...,0,14,0,0,0,0,1,0,63,0
27,111160109,160109,Couto,1989,161,133,19,0,167,63,...,1,22,0,2,3,0,0,16,89,0
28,111160113,160113,Gavieira,2019,103,114,36,18,67,34,...,0,2,0,0,0,0,0,0,31,0
29,111160113,160113,Gavieira,2009,111,113,10,3,135,72,...,0,1,0,0,0,0,0,0,8,0
30,111160113,160113,Gavieira,1999,136,114,9,1,169,81,...,0,4,0,0,0,0,0,0,57,0
31,111160113,160113,Gavieira,1989,258,176,1,0,256,116,...,0,7,0,1,0,0,1,0,95,0
32,111160115,160115,Gondoriz,2019,34,219,29,16,144,77,...,0,25,0,8,4,0,2,3,84,0
33,111160115,160115,Gondoriz,2009,108,185,21,3,170,80,...,0,17,0,1,0,0,2,3,100,0
34,111160115,160115,Gondoriz,1999,231,229,17,9,185,89,...,0,39,0,4,1,0,1,3,146,0
35,111160115,160115,Gondoriz,1989,362,338,19,4,456,171,...,0,30,0,1,0,0,0,0,177,0
36,111160121,160121,Miranda,2019,40,72,3,2,58,36,...,1,8,0,4,5,4,17,2,55,0
37,111160121,160121,Miranda,2009,74,70,6,1,73,44,...,0,4,0,0,0,0,2,0,33,0
38,111160121,160121,Miranda,1999,141,72,6,1,123,59,...,0,9,0,1,2,0,1,0,61,0
39,111160121,160121,Miranda,1989,364,105,0,0,296,126,...,0,3,0,0,0,0,0,0,66,0
40,111160122,160122,Monte Redondo,2019,5,55,6,3,16,9,...,0,5,0,3,3,2,2,0,16,0
41,111160122,160122,Monte Redondo,2009,35,61,3,5,42,22,...,0,7,0,1,1,0,0,2,33,0
42,111160122,160122,Monte Redondo,1999,57,104,2,3,98,46,...,0,13,0,3,1,0,1,9,52,0
43,111160122,160122,Monte Redondo,1989,188,101,2,3,162,65,...,1,13,0,1,0,1,1,45,90,1
44,111160123,160123,Oliveira,2019,8,68,14,5,23,11,...,0,26,0,4,3,1,3,2,23,0
45,111160123,160123,Oliveira,2009,30,47,8,6,39,20,...,0,14,0,2,2,0,2,2,27,0
46,111160123,160123,Oliveira,1999,42,91,9,1,70,35,...,0,13,0,0,2,1,1,0,47,0
47,111160123,160123,Oliveira,1989,113,69,6,0,100,44,...,3,9,0,3,9,0,2,20,54,0
48,111160124,160124,PaÃ§Ã´,2019,11,49,13,13,22,12,...,0,53,2,0,0,0,3,1,22,1
49,111160124,160124,PaÃ§Ã´,2009,13,57,12,13,49,23,...,0,44,7,2,3,0,0,0,29,1

In [28]:
# Definir el mapeo de NutsID a nombres de región
nuts_to_region = {
    '111': 'Alto Minho',
    '112': 'Cávado',
    '119': 'Ave',
    '11A': 'Área Metropolitana do Porto',
    '11B': 'Alto Tâmega',
    '11C': 'Tâmega e Sousa',
    '11D': 'Douro',
    '11E': 'Terras de Trás-os-Montes',
    '16B': 'Oeste',
    '16D': 'Região de Aveiro',
    '16E': 'Região de Coimbra',
    '16F': 'Região de Leiria',
    '16G': 'Viseu Dão Lafões',
    '16H': 'Beira Baixa',
    '16I': 'Médio Tejo',
    '16J': 'Beiras e Serra da Estrela',
    '170': 'Área Metropolitana de Lisboa',
    '181': 'Alentejo Litoral',
    '184': 'Baixo Alentejo',
    '185': 'Lezíria do Tejo',
    '186': 'Alto Alentejo',
    '187': 'Alentejo Central',
    '150': 'Algarve'   
}

# Crear una función para extraer los nombres de región de los códigos NutsID
def get_region_name(nutsid):
    # Extraer los primeros 4 caracteres del NutsID para el mapeo
    prefix = nutsid[:3]
    # Devolver el nombre de la región correspondiente
    return nuts_to_region.get(prefix, 'Unknown')

# Añadir una nueva columna al DataFrame con los nombres de región
df['Region_N4'] = df['NutsID'].apply(get_region_name)

# Imprimir las primeras filas del DataFrame resultante
df.head()

,NutsID,DICOFRE,region_name,year,edu_none,edu_basic,edu_secondary,edu_superior,labour_family,labour_holder,...,other_permanent_crop_area,fresh_fruit_holdings,citrus_holdings,fruit_holdings,nuts_holdings,olive_holdings,vineyard_holdings,other_permanent_crop_holdings,Region,Region_N4
0,111160101,160101,Aboim das ChoÃ§as,2019,15,61,11,7,34,15,...,0,0,1,0,1,0,32,0,Unknown,Alto Minho
1,111160101,160101,Aboim das ChoÃ§as,2009,30,57,4,4,50,24,...,0,0,0,0,0,0,29,0,Unknown,Alto Minho
2,111160101,160101,Aboim das ChoÃ§as,1999,49,73,7,6,62,26,...,0,0,0,0,0,0,40,0,Unknown,Alto Minho
3,111160101,160101,Aboim das ChoÃ§as,1989,167,97,4,0,163,70,...,0,0,0,0,0,1,84,0,Unknown,Alto Minho
4,111160102,160102,AguiÃ£,2019,24,68,5,2,70,38,...,0,0,0,0,0,2,39,0,Unknown,Alto Minho

In [30]:
# Definir el mapeo de NutsID a nombres de región
nuts_to_region = {
    '11': 'Norte',
    '16': 'Centro',
    '17': 'Área Metropolitana de Lisboa',
    '18': 'Alentejo',
    '15': 'Algarve'  
}

# Crear una función para extraer los nombres de región de los códigos NutsID
def get_region_name(nutsid):
    # Extraer los primeros 4 caracteres del NutsID para el mapeo
    prefix = nutsid[:2]
    # Devolver el nombre de la región correspondiente
    return nuts_to_region.get(prefix, 'Unknown')

# Añadir una nueva columna al DataFrame con los nombres de región
df['Region'] = df['NutsID'].apply(get_region_name)

# Imprimir las primeras filas del DataFrame resultante
df.head()

,NutsID,DICOFRE,region_name,year,edu_none,edu_basic,edu_secondary,edu_superior,labour_family,labour_holder,...,other_permanent_crop_area,fresh_fruit_holdings,citrus_holdings,fruit_holdings,nuts_holdings,olive_holdings,vineyard_holdings,other_permanent_crop_holdings,Region,Region_N4
0,111160101,160101,Aboim das ChoÃ§as,2019,15,61,11,7,34,15,...,0,0,1,0,1,0,32,0,Norte,Alto Minho
1,111160101,160101,Aboim das ChoÃ§as,2009,30,57,4,4,50,24,...,0,0,0,0,0,0,29,0,Norte,Alto Minho
2,111160101,160101,Aboim das ChoÃ§as,1999,49,73,7,6,62,26,...,0,0,0,0,0,0,40,0,Norte,Alto Minho
3,111160101,160101,Aboim das ChoÃ§as,1989,167,97,4,0,163,70,...,0,0,0,0,0,1,84,0,Norte,Alto Minho
4,111160102,160102,AguiÃ£,2019,24,68,5,2,70,38,...,0,0,0,0,0,2,39,0,Norte,Alto Minho

In [29]:
# Contar el número de registros donde la región es 'Unknown'
unknown_count = df[df['Region_N4'] == 'Unknown'].shape[0]

# Imprimir el conteo
print("Número de registros con región desconocida:", unknown_count)

Número de registros con región desconocida: 0

In [31]:
# Contar el número de registros donde la región es 'Unknown'
unknown_count = df[df['Region'] == 'Unknown'].shape[0]

# Imprimir el conteo
print("Número de registros con región desconocida:", unknown_count)

Número de registros con región desconocida: 0